---
- name: check if f1 folder is present on all servers if not create f1 file
  hosts: all
  tasks:
   - name: check if f1 folder is present
     stat:
       path: /home/ubuntu/f1
     register: a
   - name: display above module output
     debug:
       var: a
   - name: create f1 file if f1 dir is not present
     file:
      name: /home/ubuntu/f1
      state: touch
     when: a.stat.exists == false   

...
